### PR TITLE
Update gemspec and version number

### PR DESCRIPTION
**Pull request by BenSandeen**
Forked repo into Drip org

Update gemspec to allow omniauth 1 and 2 in order to update

### CODE REVIEW

**Comment by BenSandeen** [comment]
bump

**Review by atongen — COMMENTED** [review]
This change seems fine to me. Has this been tested in the monolith?

**Comment by BenSandeen** [comment]
> This change seems fine to me. Has this been tested in the monolith?

First off, it's almost 9pm your time!  Thanks for taking a look, but feel free to wait until later to think more about this :P

And to answer your question, not yet.  Andrew Maggert (see footnote below) has ostensibly added the private FE URLs to some list with Facebook that will allow us to test this on a private instance, but I haven't yet done so: https://getdrip.slack.com/archives/C02B6MPRYDS/p1676575733938969?thread_ts=1675899552.094159&cid=C02B6MPRYDS

*I've asked around, and apparently Andrew Maggert (and possibly Mike Nadel) is (are) the only one(s) with the ability to manage our integration: https://getdrip.slack.com/archives/C02B6MPRYDS/p1676568933672359?thread_ts=1675899552.094159&cid=C02B6MPRYDS

Not something to fix right now, but also something that is a pretty brittle point for this integration

**Comment by BenSandeen** [comment]
Also, we're not currently using this fork of the gem, so merging in this PR shouldn't break anything; if it doesn't work, I'll learn that when testing updating the monolith to use this fork and I'll figure out how to fix things then

**Comment by atongen** [comment]
You can test this branch of this repo in a feature branch in the monolith prior to merging this PR.

**Comment by BenSandeen** [comment]
> You can test this branch of this repo in a feature branch in the monolith prior to merging this PR.

@atongen  I've tested on private1 that this doesn't break our ability to integrate with FB.  Here's the PR: https://github.com/DripEmail/drip/pull/25719

**Comment by BenSandeen** [comment]
Wait, I'm getting things mixed up; I don't think we actually need this PR, since the gemspec doesn't specify a version of `omniauth`, just `omniauth-oauth2`

**Pull request closed without merging**
